const HOUSES = {
  stark:{name:"House Stark",sigil:'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 60 60" width="40" height="40"><rect width="60" height="60" fill="#f0f0f0" rx="3"/><path d="M10 42 C10 42 12 36 14 34 C13 30 14 26 18 24 C18 24 16 20 17 17 C19 19 20 20 22 20 C24 17 27 15 30 15 C33 15 36 16 38 19 C40 18 42 17 44 18 C43 21 42 24 43 26 C46 28 47 32 46 36 C48 38 49 42 49 42 L44 40 C43 43 41 46 38 47 L37 44 C35 46 32 47 30 47 C28 47 25 46 23 44 L22 47 C19 46 17 43 16 40 Z" fill="#808080" stroke="#555" stroke-width="1"/><circle cx="24" cy="23" r="2" fill="#1a1a1a"/><circle cx="36" cy="23" r="2" fill="#1a1a1a"/><path d="M26 30 Q30 34 34 30" stroke="#1a1a1a" stroke-width="1.5" fill="none"/><path d="M18 17 L14 10 M18 19 L13 14" stroke="#808080" stroke-width="2" stroke-linecap="round"/><path d="M42 18 L46 11 M42 20 L47 15" stroke="#808080" stroke-width="2" stroke-linecap="round"/></svg>',words:'"Winter is Coming"',region:"The North",seat:"Winterfell",color:"#4a6080",
    characters:["eddard","robb","sansa","arya","bran","catelyn"]},
  lannister:{name:"House Lannister",sigil:'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 60 60" width="40" height="40"><rect width="60" height="60" fill="#8b0000" rx="3"/><path d="M30 8 C26 8 22 11 20 14 C17 12 14 13 13 16 C15 18 17 19 19 19 C17 22 17 26 19 29 L17 32 L20 31 L21 35 L24 32 C26 34 28 35 30 35 C32 35 34 34 36 32 L39 35 L40 31 L43 32 L41 29 C43 26 43 22 41 19 C43 19 45 18 47 16 C46 13 43 12 40 14 C38 11 34 8 30 8Z" fill="#FFD700" stroke="#c9a84c" stroke-width="1"/><path d="M24 35 L22 44 L30 40 L38 44 L36 35" fill="#FFD700" stroke="#c9a84c" stroke-width="1"/><circle cx="25" cy="20" r="2" fill="#8b0000"/><circle cx="35" cy="20" r="2" fill="#8b0000"/><path d="M26 26 Q30 30 34 26" stroke="#8b0000" stroke-width="1.5" fill="none"/><path d="M20 14 C18 10 20 7 23 8" stroke="#FFD700" stroke-width="2" fill="none" stroke-linecap="round"/><path d="M40 14 C42 10 40 7 37 8" stroke="#FFD700" stroke-width="2" fill="none" stroke-linecap="round"/></svg>',words:'"Hear Me Roar"',region:"The Westerlands",seat:"Casterly Rock",color:"#806030",
    characters:["tywin","cersei","jaime","tyrion"]},
  baratheon:{name:"House Baratheon",sigil:'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 60 60" width="40" height="40"><rect width="60" height="60" fill="#FFD700" rx="3"/><path d="M22 38 L22 28 C18 26 15 22 15 18 C15 14 18 12 20 13" fill="none" stroke="#1a1a1a" stroke-width="3" stroke-linecap="round"/><path d="M38 38 L38 28 C42 26 45 22 45 18 C45 14 42 12 40 13" fill="none" stroke="#1a1a1a" stroke-width="3" stroke-linecap="round"/><ellipse cx="30" cy="28" rx="10" ry="13" fill="#1a1a1a"/><path d="M20 13 L16 6 M20 13 L14 10 M20 14 L17 7" stroke="#1a1a1a" stroke-width="2.5" stroke-linecap="round"/><path d="M40 13 L44 6 M40 13 L46 10 M40 14 L43 7" stroke="#1a1a1a" stroke-width="2.5" stroke-linecap="round"/><circle cx="26" cy="25" r="2" fill="#FFD700"/><circle cx="34" cy="25" r="2" fill="#FFD700"/><path d="M23 5 L25 8 L27 6 L29 9 L31 6 L33 8 L35 5 L37 8 L23 8 Z" fill="#1a1a1a"/><ellipse cx="26" cy="44" rx="4" ry="6" fill="#1a1a1a"/><ellipse cx="34" cy="44" rx="4" ry="6" fill="#1a1a1a"/></svg>',words:'"Ours is the Fury"',region:"The Stormlands",seat:"Storm\'s End",color:"#303050",
    characters:["robert","stannis","renly","gendry"]},
  targaryen:{name:"House Targaryen",sigil:'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 60 60" width="40" height="40"><rect width="60" height="60" fill="#1a1a1a" rx="3"/><path d="M30 10 C27 10 24 13 24 16 L20 14 L22 18 C19 18 17 20 18 23 L22 22 L20 26 C22 28 25 29 28 28 L28 32 L24 38 L30 35 L36 38 L32 32 L32 28 C35 29 38 28 40 26 L38 22 L42 23 C43 20 41 18 38 18 L40 14 L36 16 C36 13 33 10 30 10Z" fill="#8b0000" stroke="#c00" stroke-width="1"/><path d="M18 30 L12 26 L14 32 L10 32 L14 36 L12 40 L18 37" fill="#8b0000" stroke="#c00" stroke-width="1"/><path d="M42 30 L48 26 L46 32 L50 32 L46 36 L48 40 L42 37" fill="#8b0000" stroke="#c00" stroke-width="1"/><circle cx="27" cy="18" r="1.5" fill="#FFD700"/><circle cx="33" cy="18" r="1.5" fill="#FFD700"/></svg>',words:'"Fire and Blood"',region:"Dragonstone / Essos",seat:"Dragonstone",color:"#602030",
    characters:["daenerys","viserys","rhaegar","aerys"]},
  greyjoy:{name:"House Greyjoy",sigil:'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 60 60" width="40" height="40"><rect width="60" height="60" fill="#1a1a1a" rx="3"/><ellipse cx="30" cy="22" rx="11" ry="9" fill="#FFD700" stroke="#c9a84c" stroke-width="1"/><ellipse cx="30" cy="18" rx="6" ry="4" fill="#c9a84c"/><circle cx="26" cy="20" r="1.5" fill="#1a1a1a"/><circle cx="34" cy="20" r="1.5" fill="#1a1a1a"/><path d="M19 28 Q14 36 12 48" stroke="#FFD700" stroke-width="3.5" stroke-linecap="round" fill="none"/><path d="M22 30 Q18 40 17 50" stroke="#FFD700" stroke-width="3.5" stroke-linecap="round" fill="none"/><path d="M26 31 Q24 42 24 52" stroke="#FFD700" stroke-width="3.5" stroke-linecap="round" fill="none"/><path d="M30 31 Q30 42 30 52" stroke="#FFD700" stroke-width="3.5" stroke-linecap="round" fill="none"/><path d="M34 31 Q36 42 36 52" stroke="#FFD700" stroke-width="3.5" stroke-linecap="round" fill="none"/><path d="M38 30 Q42 40 43 50" stroke="#FFD700" stroke-width="3.5" stroke-linecap="round" fill="none"/><path d="M41 28 Q46 36 48 48" stroke="#FFD700" stroke-width="3.5" stroke-linecap="round" fill="none"/></svg>',words:'"We Do Not Sow"',region:"The Iron Islands",seat:"Pyke",color:"#1a2a3a",
    characters:["balon","theon","yara","euron"]},
  tully:{name:"House Tully",sigil:'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 60 60" width="40" height="40"><rect width="60" height="60" fill="#1a3a8b" rx="3"/><rect x="0" y="40" width="60" height="20" fill="#8b0000" rx="0"/><path d="M8 30 C8 30 22 12 38 22 L52 30 L38 38 C22 48 8 30 8 30Z" fill="#C0C0C0" stroke="#a0a0a0" stroke-width="1"/><path d="M38 22 L52 14 L50 30 L52 46 L38 38" fill="#C0C0C0" stroke="#a0a0a0" stroke-width="1"/><path d="M14 27 Q20 22 28 24 M14 30 Q20 30 28 30 M14 33 Q20 38 28 36" stroke="#8888aa" stroke-width="1" fill="none" opacity="0.6"/><circle cx="18" cy="29" r="2.5" fill="#c9a84c"/></svg>',words:'"Family, Duty, Honour"',region:"The Riverlands",seat:"Riverrun",color:"#1a3a4a",
    characters:["hoster","edmure","catelyn","brynden"]},
  arryn:{name:"House Arryn",sigil:'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 60 60" width="40" height="40"><rect width="60" height="60" fill="#4a90d9" rx="3"/><circle cx="30" cy="30" r="18" fill="white" opacity="0.9"/><circle cx="36" cy="26" r="14" fill="#4a90d9"/><path d="M20 28 C20 28 16 22 20 18 C22 18 24 20 26 20 C28 16 32 14 30 18 C32 16 38 14 36 20 C40 18 44 20 42 24 L36 22 L34 28 L40 32 L32 30 L30 38 L28 30 L20 32 L26 28 Z" fill="#1a3a6a" stroke="#0a2a5a" stroke-width="0.5"/><path d="M28 38 L26 46 L30 42 L34 46 L32 38" fill="#1a3a6a" stroke="#0a2a5a" stroke-width="0.5"/><circle cx="27" cy="22" r="1.5" fill="#FFD700"/></svg>',words:'"As High as Honour"',region:"The Vale",seat:"The Eyrie",color:"#1a3a5a",
    characters:["jon_arryn","lysa","robin"]},
  tyrell:{name:"House Tyrell",sigil:'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 60 60" width="40" height="40"><rect width="60" height="60" fill="#2d6a2d" rx="3"/><line x1="30" y1="52" x2="30" y2="26" stroke="#1a4a1a" stroke-width="3"/><path d="M30 44 C22 42 18 36 20 30 C24 34 27 38 30 44Z" fill="#1a4a1a"/><path d="M30 44 C38 42 42 36 40 30 C36 34 33 38 30 44Z" fill="#1a4a1a"/><path d="M30 38 C24 34 22 26 26 22 C27 26 28 30 30 38Z" fill="#1a5a1a"/><circle cx="30" cy="18" r="10" fill="#FFD700" stroke="#c9a84c" stroke-width="1.5"/><circle cx="30" cy="18" r="6" fill="#e8b800"/><circle cx="30" cy="18" r="3" fill="#FFD700"/><path d="M20 12 Q25 7 30 10 Q25 8 20 12Z" fill="#FFD700" opacity="0.8"/><path d="M40 12 Q35 7 30 10 Q35 8 40 12Z" fill="#FFD700" opacity="0.8"/><path d="M20 24 Q25 29 30 26 Q25 28 20 24Z" fill="#FFD700" opacity="0.8"/><path d="M40 24 Q35 29 30 26 Q35 28 40 24Z" fill="#FFD700" opacity="0.8"/><path d="M16 18 Q18 12 22 14 Q18 14 16 18Z" fill="#FFD700" opacity="0.8"/><path d="M44 18 Q42 12 38 14 Q42 14 44 18Z" fill="#FFD700" opacity="0.8"/></svg>',words:'"Growing Strong"',region:"The Reach",seat:"Highgarden",color:"#1a3a1a",
    characters:["mace","olenna","margaery","loras"]},
  martell:{name:"House Martell",sigil:'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 60 60" width="40" height="40"><rect width="60" height="60" fill="#c8601a" rx="3"/><circle cx="30" cy="30" r="12" fill="#c00000" stroke="#FFD700" stroke-width="1.5"/><line x1="30" y1="4" x2="30" y2="14" stroke="#FFD700" stroke-width="2" stroke-linecap="round"/><line x1="30" y1="46" x2="30" y2="56" stroke="#FFD700" stroke-width="2" stroke-linecap="round"/><line x1="4" y1="30" x2="14" y2="30" stroke="#FFD700" stroke-width="2" stroke-linecap="round"/><line x1="46" y1="30" x2="56" y2="30" stroke="#FFD700" stroke-width="2" stroke-linecap="round"/><line x1="11" y1="11" x2="18" y2="18" stroke="#FFD700" stroke-width="2" stroke-linecap="round"/><line x1="42" y1="42" x2="49" y2="49" stroke="#FFD700" stroke-width="2" stroke-linecap="round"/><line x1="49" y1="11" x2="42" y2="18" stroke="#FFD700" stroke-width="2" stroke-linecap="round"/><line x1="18" y1="42" x2="11" y2="49" stroke="#FFD700" stroke-width="2" stroke-linecap="round"/><line x1="48" y1="6" x2="16" y2="52" stroke="#FFD700" stroke-width="2.5" stroke-linecap="round"/><polygon points="48,6 44,12 52,10" fill="#FFD700"/></svg>',words:'"Unbowed, Unbent, Unbroken"',region:"Dorne",seat:"Sunspear",color:"#4a2a10",
    characters:["doran","oberyn","elia","arianne"]}
};

const CHARACTERS = {
  eddard:{name:"Eddard Stark",title:"Lord of Winterfell, Hand of the King",house:"stark",portrait:"🧔",
    bio:"Eddard 'Ned' Stark was Lord of Winterfell and Warden of the North, renowned for his unshakeable honour. Raised alongside Robert Baratheon in the Vale, he fought in Robert's Rebellion. A man carved from grey granite, ill-suited for the vipers' nest of King's Landing.",
    battles:["Siege of Storm's End","Sack of King's Landing","Greyjoy's Rebellion"],
    moments:"His refusal to compromise his honour before the Great Sept of Baelor defined his character until his final breath.",
    lineage_detail:"Father of Robb, Sansa, Arya, Bran, and Rickon. Putative father of Jon Snow.",
    status:"dead",status_text:"Executed at the Sept of Baelor"},
  robb:{name:"Robb Stark",title:"King in the North",house:"stark",portrait:"👦",
    bio:"Undefeated in open battle, the Young Wolf was a commander of rare talent who never lost on the field, yet fell to treachery at the hands of Roose Bolton and Walder Frey at the Red Wedding.",
    battles:["Battle of the Whispering Wood","Battle of the Camps","Battle of Oxcross","The Red Wedding"],
    moments:"His breaking of his betrothal oath to a Frey daughter was the seed of his destruction. His direwolf Grey Wind fell with him at the Twins.",
    lineage_detail:"Son of Eddard and Catelyn Stark.",status:"dead",status_text:"Slain at the Red Wedding"},
  sansa:{name:"Sansa Stark",title:"Lady of Winterfell",house:"stark",portrait:"👸",
    bio:"Raised on songs of knights and fair ladies, Sansa's romantic vision shattered in King's Landing. Hostage to the Lannisters, she endured years of humiliation, learning politics from Cersei and Littlefinger alike.",
    battles:["Battle of the Blackwater (civilian)","Battle of the Bastards"],
    moments:"Her transformation from pawn to player — from King's Landing to the Vale to Winterfell — is one of the great arcs of the age.",
    lineage_detail:"Daughter of Eddard and Catelyn Stark.",status:"alive",status_text:"Queen in the North"},
  arya:{name:"Arya Stark",title:"No One / Arya of House Stark",house:"stark",portrait:"👧",
    bio:"Never content with the life of a lady, Arya trained under Syrio Forel, survived the roads of Westeros in disguise, and crossed the Narrow Sea to study with the Faceless Men in Braavos.",
    battles:["Harrenhal","Various skirmishes across the Riverlands"],
    moments:"Her list became her prayer. Each name crossed off was a debt repaid in the old language of steel.",
    lineage_detail:"Daughter of Eddard and Catelyn Stark.",status:"alive",status_text:"Sailing west of Westeros"},
  bran:{name:"Brandon Stark",title:"The Three-Eyed Raven",house:"stark",portrait:"🧒",
    bio:"Pushed from a tower window by Jaime Lannister, Bran lost his legs but gained greensight. His visions led him beyond the Wall, where he underwent a transformation that left him barely human.",
    battles:["Fall of Winterfell"],
    moments:"Holding the door with Hodor — living the moment twice — is among the most devastating events in the chronicles of ice and fire.",
    lineage_detail:"Son of Eddard and Catelyn Stark.",status:"alive",status_text:"King of the Six Kingdoms"},
  catelyn:{name:"Catelyn Tully",title:"Lady of Winterfell",house:"stark",portrait:"👩",
    bio:"A devoted mother and shrewd noblewoman, Catelyn acted always from love for her children, even when those actions had catastrophic consequences for the realm.",
    battles:["The Red Wedding"],
    moments:"She saw each of her children taken by war or treachery. At the Red Wedding she watched her eldest son slain before her eyes.",
    lineage_detail:"Daughter of Hoster Tully. Mother of Robb, Sansa, Arya, Bran, and Rickon.",
    status:"dead",status_text:"Slain at the Red Wedding"},
  tywin:{name:"Tywin Lannister",title:"Lord of Casterly Rock",house:"lannister",portrait:"👴",
    bio:"The most powerful lord in Westeros for a generation. Cold, calculating, and utterly ruthless, he believed the only thing that mattered was legacy — the Lannister name enduring for a thousand years.",
    battles:["Reyne-Tarbeck Rebellion","Robert's Rebellion — Sack of King's Landing","War of the Five Kings"],
    moments:"The Rains of Castamere was composed to mark his annihilation of House Reyne. The song became a warning played at the Red Wedding.",
    lineage_detail:"Father of Cersei, Jaime, and Tyrion.",status:"dead",status_text:"Killed by Tyrion Lannister"},
  cersei:{name:"Cersei Lannister",title:"Queen Regent of the Seven Kingdoms",house:"lannister",portrait:"👱‍♀️",
    bio:"Twin to Jaime, daughter to Tywin. She married Robert Baratheon and spent twenty years manoeuvring in his court. Brilliant and ruthless, she played the game of thrones better than most men.",
    battles:["Battle of the Blackwater"],
    moments:"Her walk of shame through King's Landing was meant to break her. She emerged transformed — shame burned away, leaving only iron and wildfire.",
    lineage_detail:"Daughter of Tywin. Twin of Jaime. Mother of Joffrey, Myrcella, and Tommen.",
    status:"dead",status_text:"Crushed in the Red Keep's collapse"},
  jaime:{name:"Jaime Lannister",title:"Ser, Knight of the Kingsguard",house:"lannister",portrait:"⚔️",
    bio:"Called the Kingslayer for killing the king he was sworn to protect, Jaime carried that shame for decades — unable to reveal he killed Aerys to save half a million lives from wildfire.",
    battles:["Whispering Wood — captured","Raid on Riverrun"],
    moments:"The loss of his sword hand stripped away his identity entirely. His time with Brienne rebuilt him into something closer to the knight he once dreamed of being.",
    lineage_detail:"Son of Tywin. Twin brother of Cersei.",status:"dead",status_text:"Died with Cersei in the Red Keep"},
  tyrion:{name:"Tyrion Lannister",title:"The Imp, Hand of the Queen",house:"lannister",portrait:"🧙",
    bio:"Born a dwarf and blamed by his father for his mother's death, Tyrion compensated with one of the sharpest minds in the Seven Kingdoms, a gift for wine, and a sardonic wit that disarmed enemies and charmed allies alike.",
    battles:["Battle of the Blackwater — commanded the chain and wildfire"],
    moments:"His trial by combat after Joffrey's murder, and his final confrontation with his father, encapsulate his impossible position as a Lannister who despises what the name demands.",
    lineage_detail:"Son of Tywin. Brother of Cersei and Jaime.",status:"alive",status_text:"Hand of the King, last known"},
  robert:{name:"Robert Baratheon",title:"King of the Seven Kingdoms",house:"baratheon",portrait:"👑",
    bio:"Robert won his throne with a warhammer and a cause. The greatest warrior of his age, he was a catastrophic king — bored by governance, excessive in appetite, mourning Lyanna Stark until his dying day.",
    battles:["Battle of Summerhall","Battle of Ashford","Battle of the Bells","Battle of the Trident"],
    moments:"His killing of Rhaegar at the Trident — rubies scattering across the water — was the defining moment of his life. Everything after was anticlimax.",
    lineage_detail:"Son of Steffon Baratheon. Father of Gendry (bastard).",status:"dead",status_text:"Died of a hunting wound"},
  stannis:{name:"Stannis Baratheon",title:"Lord of Dragonstone, King",house:"baratheon",portrait:"⚖️",
    bio:"The most capable military commander of his age and the most joyless man in Westeros. Stannis did not seek the throne from ambition but from duty — he was the rightful heir and that was sufficient.",
    battles:["Siege of Storm's End","Battle of the Blackwater","Battle of Castle Black"],
    moments:"His sacrifice of his daughter Shireen to the fires of Melisandre shattered any remaining sympathy the realm might have afforded him.",
    lineage_detail:"Son of Steffon Baratheon. Father of Shireen.",status:"dead",status_text:"Executed by Brienne of Tarth"},
  renly:{name:"Renly Baratheon",title:"Lord of Storm's End, King",house:"baratheon",portrait:"🌹",
    bio:"The youngest and most charming of the Baratheon brothers. He raised the greatest army in the realm through force of personality alone — a quality neither Robert nor Stannis possessed.",
    battles:["No major battles — died before engagement"],
    moments:"His shadow-murder by Stannis's sorcery left his army leaderless and ended his kingship before it truly began.",
    lineage_detail:"Son of Steffon Baratheon. Husband of Margaery Tyrell.",status:"dead",status_text:"Killed by shadow assassin"},
  gendry:{name:"Gendry",title:"Lord of Storm's End",house:"baratheon",portrait:"🔨",
    bio:"Robert Baratheon's bastard son, raised as a blacksmith's apprentice. He inherited his father's build and stubbornness but none of his title — until Daenerys legitimised him.",
    battles:["Battle of Winterfell — the Long Night"],
    moments:"His forging of dragonglass weapons before the Long Night gave the realm a fighting chance against the dead.",
    lineage_detail:"Bastard son of Robert Baratheon.",status:"alive",status_text:"Lord of Storm's End"},
  daenerys:{name:"Daenerys Targaryen",title:"Khaleesi, Mother of Dragons, Breaker of Chains",house:"targaryen",portrait:"🐉",
    bio:"Born during a storm on Dragonstone the night her family was destroyed, Daenerys grew up in exile. From slave markets in Essos to the ashes of Valyrian ambition, she forged herself into a queen of fire and blood.",
    battles:["Battle of Yunkai","Battle of Meereen","Siege of Winterfell","Battle of King's Landing"],
    moments:"Stepping into Khal Drogo's funeral pyre and emerging unburnt with three newly-hatched dragons was the moment the world changed forever.",
    lineage_detail:"Daughter of Aerys II and Rhaella Targaryen. Sister of Viserys and Rhaegar.",
    status:"dead",status_text:"Killed by Jon Snow in the throne room"},
  viserys:{name:"Viserys Targaryen",title:"The Beggar King",house:"targaryen",portrait:"👤",
    bio:"The elder brother of Daenerys spent his life nursing his obsession with reclaiming the Iron Throne. He called himself the rightful king but behaved like a petulant child who never understood that dragons choose their riders.",
    battles:["No battles — died before his campaign began"],
    moments:"His golden crown — molten gold poured over his head by Khal Drogo — was the end he earned through cruelty and impatience.",
    lineage_detail:"Son of Aerys II. Brother of Daenerys.",status:"dead",status_text:"Killed by Khal Drogo"},
  rhaegar:{name:"Rhaegar Targaryen",title:"Crown Prince of Dragonstone",house:"targaryen",portrait:"🎵",
    bio:"The finest warrior of his generation and a man of deep melancholy intelligence. His harp-playing moved men to tears. His elopement with Lyanna Stark ignited the rebellion that destroyed his house.",
    battles:["Battle of the Trident"],
    moments:"At the Trident, rubies flew from his breastplate as Robert's warhammer broke him. His secret marriage to Lyanna made their son the true heir.",
    lineage_detail:"Son of Aerys II. Father of Jon Snow by Lyanna Stark.",status:"dead",status_text:"Slain by Robert Baratheon at the Trident"},
  aerys:{name:"Aerys II Targaryen",title:"The Mad King",house:"targaryen",portrait:"🔥",
    bio:"The last Targaryen king began his reign with promise and ended it in madness. His obsession with wildfire and descent into paranoia destroyed three centuries of Targaryen rule.",
    battles:["Defiance of Duskendale","Sack of King's Landing — victim"],
    moments:"His final order — 'Burn them all' — was stopped only by the sword of his own Kingsguard. Jaime Lannister killed him to save half a million lives and was never thanked for it.",
    lineage_detail:"Son of Jaehaerys II. Father of Rhaegar, Viserys, and Daenerys.",
    status:"dead",status_text:"Killed by Jaime Lannister"},
  theon:{name:"Theon Greyjoy",title:"Prince of the Iron Islands",house:"greyjoy",portrait:"⚓",
    bio:"Ward of Eddard Stark since childhood, Theon grew up between two worlds. His seizure of Winterfell shattered both identities, leading to years of captivity that unmade him entirely — until one final act of desperate courage.",
    battles:["Seizure of Winterfell","Battle of Winterfell — the Long Night"],
    moments:"Charging the Night King to protect Bran gave him the death he needed and the realm did not expect.",
    lineage_detail:"Son of Balon Greyjoy. Ward of House Stark.",status:"dead",status_text:"Died charging the Night King"},
  balon:{name:"Balon Greyjoy",title:"King of the Iron Islands",house:"greyjoy",portrait:"🦑",
    bio:"Twice a rebel king, Balon led the Iron Islands to war against Robert Baratheon and lost everything including his sons. His bitterness and pride defined the ironborn ethos of his reign.",
    battles:["Greyjoy's Rebellion"],
    moments:"His rejection of Theon upon his return from Winterfell, and his obsession with the old ways, made him enemies within his own house.",
    lineage_detail:"Father of Yara and Theon.",status:"dead",status_text:"Fell from a bridge at Pyke"},
  yara:{name:"Yara Greyjoy",title:"Lady of the Iron Islands",house:"greyjoy",portrait:"🏴",
    bio:"The eldest surviving child of Balon Greyjoy and the ironborn captain her father always wished Theon had been. Yara led longships before she led kingdoms.",
    battles:["Siege of Deepwood Motte","Various naval engagements"],
    moments:"Her daring attempt to rescue Theon from the Dreadfort showed that beneath ironborn pride ran something rarer — loyalty to blood.",
    lineage_detail:"Daughter of Balon Greyjoy. Sister of Theon.",status:"alive",status_text:"Lady of the Iron Islands"},
  euron:{name:"Euron Greyjoy",title:"King of the Iron Islands",house:"greyjoy",portrait:"⚡",
    bio:"The most dangerous and unpredictable of the Greyjoys, Euron had sailed every sea and murdered his brother Balon to seize the Seastone Chair. His ambition stretched to the Iron Throne itself.",
    battles:["Various naval raids","Battle of Dragonstone waters"],
    moments:"His alliance with Cersei and command of the Golden Company was the most audacious play for power after the War of the Five Kings.",
    lineage_detail:"Son of Quellon Greyjoy. Brother of Balon.",status:"dead",status_text:"Killed by Jaime Lannister"},
  hoster:{name:"Hoster Tully",title:"Lord Paramount of the Riverlands",house:"tully",portrait:"⚜️",
    bio:"Patriarch of House Tully, Hoster built alliances through his daughters' marriages — Catelyn to Eddard Stark, Lysa to Jon Arryn. He died before seeing the consequences of those alliances unfold.",
    battles:["Robert's Rebellion"],
    moments:"His forcing of Lysa to abort Littlefinger's child haunted his deathbed. He died with the word 'tansy' on his lips.",
    lineage_detail:"Father of Catelyn, Lysa, and Edmure.",status:"dead",status_text:"Died of illness at Riverrun"},
  edmure:{name:"Edmure Tully",title:"Lord of Riverrun",house:"tully",portrait:"🐟",
    bio:"The son and heir of Hoster Tully, Edmure was a decent man with a good heart who was consistently outmanoeuvred by circumstances and cleverer enemies.",
    battles:["Battle of Stone Mill","Red Wedding — captured"],
    moments:"His impulsive attack at Stone Mill — well-intentioned and strategically disastrous — exemplified his character perfectly.",
    lineage_detail:"Son of Hoster Tully. Brother of Catelyn and Lysa.",status:"alive",status_text:"Lord of Riverrun"},
  catelyn_tully:{name:"Lysa Tully",title:"Lady of the Eyrie",house:"tully",portrait:"😰",
    bio:"Forced to abort her child by Littlefinger and married to Jon Arryn, Lysa's years in the Eyrie bred paranoid obsessive love. She murdered Jon Arryn at Littlefinger's urging — the spark that ignited the entire conflict.",
    battles:["None"],
    moments:"She died at the Moon Door — pushed through it by the very man she had killed for.",
    lineage_detail:"Daughter of Hoster Tully. Wife of Jon Arryn. Mother of Robin Arryn.",
    status:"dead",status_text:"Pushed through the Moon Door by Littlefinger"},
  brynden:{name:"Brynden Tully",title:"The Blackfish",house:"tully",portrait:"🗡️",
    bio:"The Blackfish refused a marriage arranged for him and spent his life earning his own reputation. One of the finest military commanders of his generation, his unbending character endured to the last.",
    battles:["War of the Ninepenny Kings","Robert's Rebellion","Siege of Riverrun"],
    moments:"His escape from the Red Wedding and defiant last stand at Riverrun — refusing to surrender a castle that was his family's seat — are the acts of a man who bowed to no one.",
    lineage_detail:"Brother of Hoster Tully. Uncle of Catelyn, Lysa, and Edmure.",
    status:"dead",status_text:"Killed during retaking of Riverrun"},
  jon_arryn:{name:"Jon Arryn",title:"Hand of the King, Lord of the Eyrie",house:"arryn",portrait:"🦅",
    bio:"Foster father of both Eddard Stark and Robert Baratheon. His quiet investigation into the secret of Joffrey's parentage set the entire saga in motion — and earned him a poisoner's death.",
    battles:["Robert's Rebellion"],
    moments:"His final words were 'The seed is strong.' His murder — the first in a war that claimed hundreds of thousands — went unavenged for years.",
    lineage_detail:"Lord of the Eyrie. Husband of Lysa Tully. Foster father of Eddard Stark and Robert Baratheon.",
    status:"dead",status_text:"Poisoned by his wife Lysa"},
  lysa:{name:"Lysa Tully",title:"Lady of the Eyrie",house:"arryn",portrait:"😰",
    bio:"Forced to abort her child by Littlefinger and married to Jon Arryn, Lysa's years in the Eyrie bred a paranoid, obsessive love — for Littlefinger, for her son Robin, and for safety above all else.",
    battles:["None"],
    moments:"Her murder of Jon Arryn at Littlefinger's urging was the spark that ignited everything. She died at the Moon Door — pushed through it by the man she had killed for.",
    lineage_detail:"Daughter of Hoster Tully. Wife of Jon Arryn. Mother of Robin Arryn.",
    status:"dead",status_text:"Pushed through the Moon Door by Littlefinger"},
  robin:{name:"Robin Arryn",title:"Lord of the Eyrie",house:"arryn",portrait:"👶",
    bio:"The sickly, spoilt son of Jon Arryn and Lysa Tully, Robin was his mother's obsession and her shield from the world. Wholly unfit for the responsibilities his name demanded.",
    battles:["None"],
    moments:"His casual demands that guests be sent 'through the Moon Door' were a reminder of what unchecked lordly power could become.",
    lineage_detail:"Son of Jon Arryn and Lysa Tully.",status:"alive",status_text:"Lord of the Eyrie"},
  mace:{name:"Mace Tyrell",title:"Lord of Highgarden",house:"tyrell",portrait:"🌸",
    bio:"The lord of the most fertile lands in Westeros was, by universal consensus, pompous and not particularly clever. His greatest accomplishments were his mother's strategies and his children's talents.",
    battles:["Siege of Storm's End — sat and waited"],
    moments:"His 'siege' of Storm's End — doing nothing while Davos smuggled onions to the besieged — became a gentle joke that never fully left him.",
    lineage_detail:"Son of Luthor Tyrell. Father of Margaery and Loras.",status:"dead",status_text:"Killed in the Sept of Baelor explosion"},
  olenna:{name:"Olenna Tyrell",title:"Queen of Thorns",house:"tyrell",portrait:"👵",
    bio:"The sharpest tongue in Westeros. Where her son Mace was pompous and ineffectual, Olenna was the real power behind the Tyrell rose — scheming, witty, and utterly unsentimental.",
    battles:["Political warfare in King's Landing"],
    moments:"'Tell Cersei. I want her to know it was me.' — delivered with serene malice after taking the poison Jaime brought her. One of the great exits in the chronicles.",
    lineage_detail:"Born of House Redwyne. Grandmother of Margaery and Loras.",
    status:"dead",status_text:"Poisoned herself rather than be executed"},
  margaery:{name:"Margaery Tyrell",title:"Queen of the Seven Kingdoms",house:"tyrell",portrait:"🌹",
    bio:"Three times a queen. Margaery possessed an almost supernatural gift for winning people's love. Behind her warmth was a precise political intelligence that matched Cersei's own.",
    battles:["Battle of the Blackwater — political support"],
    moments:"Her mastery of public relations — visiting orphanages, distributing bread — gave her a popularity that Cersei could never match and never forgave.",
    lineage_detail:"Daughter of Mace Tyrell. Granddaughter of Olenna. Married Renly, Joffrey, then Tommen.",
    status:"dead",status_text:"Killed in the Sept of Baelor explosion"},
  loras:{name:"Loras Tyrell",title:"Knight of Flowers",house:"tyrell",portrait:"🗡️",
    bio:"The most celebrated tourney knight of his generation. Loras won hearts across Westeros with his skill and beauty. His private grief at Renly Baratheon's death was the one thing he could never speak of openly.",
    battles:["Battle of the Blackwater","Siege of Dragonstone"],
    moments:"His imprisonment and broken confession extracted by months of captivity were a humiliation his family could not prevent.",
    lineage_detail:"Son of Mace Tyrell. Brother of Margaery.",status:"dead",status_text:"Killed in the Sept of Baelor explosion"},
  doran:{name:"Doran Martell",title:"Prince of Dorne",house:"martell",portrait:"☀️",
    bio:"The cautious elder brother of Oberyn ruled Dorne from his wheelchair with all the speed of the tide — inexorably, if slowly. His plans for revenge against the Lannisters spanned decades.",
    battles:["None directly — a patient strategist"],
    moments:"His revelation to Arianne of his long game — Targaryen alliance, patient accumulation of pieces — showed a mind that thought in years when others thought in days.",
    lineage_detail:"Brother of Oberyn and Elia. Father of Arianne and Quentyn.",
    status:"dead",status_text:"Assassinated by the Sand Snakes"},
  oberyn:{name:"Oberyn Martell",title:"The Red Viper of Dorne",house:"martell",portrait:"🐍",
    bio:"The most dangerous man in Dorne — perhaps in all of Westeros. A warrior, scholar, lover, and poisoner who never forgave and never forgot. He came to King's Landing for justice for his sister Elia.",
    battles:["Various battles in Dorne","Trial by Combat vs. Gregor Clegane"],
    moments:"He had the Mountain beaten. He only needed to finish it — but he wanted a confession first. He wanted the name. That want cost him everything.",
    lineage_detail:"Son of Prince Martell. Brother of Doran and Elia. Father of the Sand Snakes.",
    status:"dead",status_text:"Killed by Gregor Clegane during trial by combat"},
  elia:{name:"Elia Martell",title:"Princess of Dorne, Crown Princess",house:"martell",portrait:"🌺",
    bio:"The gentle, cultured wife of Rhaegar Targaryen and mother of his children, Elia was caught in a war she played no part in making. Her murder during the Sack of King's Landing haunted Dorne for a generation.",
    battles:["None — civilian"],
    moments:"Her death and the manner of it became Oberyn's lifelong wound and Dorne's enduring grievance against the Lannisters. She deserved better than history gave her.",
    lineage_detail:"Daughter of Prince Martell. Wife of Rhaegar Targaryen. Mother of Rhaenys and Aegon.",
    status:"dead",status_text:"Murdered during the Sack of King's Landing"},
  arianne:{name:"Arianne Martell",title:"Princess of Dorne",house:"martell",portrait:"🌙",
    bio:"The elder daughter of Doran and his intended heir, Arianne spent years believing her father planned to disinherit her. Her schemes to crown Myrcella queen were her attempt to seize her destiny before it was taken.",
    battles:["Myrcella incident in the Water Gardens"],
    moments:"Her confrontation with her father — and his revelation of the true depth of his plotting — transformed her understanding of patience and power.",
    lineage_detail:"Daughter of Doran Martell.",status:"alive",status_text:"Princess of Dorne, envoy to the Golden Company"}
};

const LOCATIONS = [
  {id:"winterfell",name:"Winterfell",house:"stark",x:19,y:14,desc:"Seat of House Stark, ancient castle of the Kings of Winter, warmed by hot springs beneath its walls."},
  {id:"kingslanding",name:"King's Landing",house:"baratheon",x:26,y:53,desc:"Capital of the Seven Kingdoms, home of the Iron Throne and the Red Keep."},
  {id:"casterly_rock",name:"Casterly Rock",house:"lannister",x:18,y:44,desc:"Seat of House Lannister, built into a great rock above goldmines of legendary wealth."},
  {id:"dragonstone",name:"Dragonstone",house:"targaryen",x:30,y:50,desc:"Island fortress of House Targaryen. Ancient seat of the heir to the Iron Throne. Dragons were born here."},
  {id:"the_eyrie",name:"The Eyrie",house:"arryn",x:27,y:33,desc:"Sky fortress of House Arryn, perched atop the Mountains of the Moon. Impregnable by force."},
  {id:"highgarden",name:"Highgarden",house:"tyrell",x:18,y:62,desc:"Seat of House Tyrell in the heart of the Reach, the most fertile lands of Westeros."},
  {id:"storms_end",name:"Storm's End",house:"baratheon",x:28,y:62,desc:"Mighty castle of House Baratheon on Shipbreaker Bay, built to face endless storms."},
  {id:"riverrun",name:"Riverrun",house:"tully",x:20,y:39,desc:"Island fortress of House Tully at the fork of the Red Fork and the Tumblestone rivers."},
  {id:"pyke",name:"Pyke",house:"greyjoy",x:10,y:34,desc:"Wave-battered seat of House Greyjoy on the Iron Islands, built on sea stacks above a grey sea."},
  {id:"sunspear",name:"Sunspear",house:"martell",x:27,y:76,desc:"Sandstone seat of House Martell in the deserts of Dorne, ancient and unbowed."},
  {id:"pentos",name:"Pentos",house:null,x:48,y:42,desc:"Free city of Essos where Daenerys Targaryen began her journey to reclaim her birthright."},
  {id:"dothraki",name:"Dothraki Sea",house:null,x:68,y:40,desc:"The great grasslands of Essos, home to the horse lords and their vast khalasars."},
  {id:"the_twins",name:"The Twins",house:null,x:21,y:28,desc:"Twin castles of House Frey straddling the Green Fork. Site of the infamous Red Wedding."},
  {id:"harrenhal",name:"Harrenhal",house:null,x:24,y:40,desc:"The largest castle ever built, now a cursed ruin since Aegon's dragons melted its towers."}
];
