const HOUSES = {
  stark:{name:"House Stark",sigil:'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 50 50" width="36" height="36"><path d="M25 4 C18 4 10 10 10 18 C10 24 13 28 16 30 L12 46 L25 38 L38 46 L34 30 C37 28 40 24 40 18 C40 10 32 4 25 4Z" fill="#6a8aaa" stroke="#c9a84c" stroke-width="1.5"/><circle cx="19" cy="17" r="2.5" fill="#1a0a00"/><circle cx="31" cy="17" r="2.5" fill="#1a0a00"/><path d="M20 24 Q25 28 30 24" stroke="#1a0a00" stroke-width="1.5" fill="none"/><path d="M12 12 L8 6 M13 10 L9 5" stroke="#6a8aaa" stroke-width="1.5"/><path d="M38 12 L42 6 M37 10 L41 5" stroke="#6a8aaa" stroke-width="1.5"/></svg>',words:'"Winter is Coming"',region:"The North",seat:"Winterfell",color:"#4a6080",
    characters:["eddard","robb","sansa","arya","bran","catelyn"]},
  lannister:{name:"House Lannister",sigil:'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 50 50" width="36" height="36"><ellipse cx="25" cy="22" rx="14" ry="12" fill="#c9a84c" stroke="#8a6a1a" stroke-width="1.5"/><path d="M11 18 C6 14 5 8 8 6 C10 8 11 12 13 14" fill="#c9a84c" stroke="#8a6a1a" stroke-width="1"/><path d="M39 18 C44 14 45 8 42 6 C40 8 39 12 37 14" fill="#c9a84c" stroke="#8a6a1a" stroke-width="1"/><path d="M15 12 C12 6 14 2 18 3" fill="none" stroke="#8a6a1a" stroke-width="1.5"/><path d="M35 12 C38 6 36 2 32 3" fill="none" stroke="#8a6a1a" stroke-width="1.5"/><circle cx="20" cy="20" r="2" fill="#1a0a00"/><circle cx="30" cy="20" r="2" fill="#1a0a00"/><path d="M22 26 Q25 29 28 26" stroke="#8a6a1a" stroke-width="1.5" fill="none"/><path d="M19 32 L16 44 L25 38 L34 44 L31 32" fill="#c9a84c" stroke="#8a6a1a" stroke-width="1"/></svg>',words:'"Hear Me Roar"',region:"The Westerlands",seat:"Casterly Rock",color:"#806030",
    characters:["tywin","cersei","jaime","tyrion"]},
  baratheon:{name:"House Baratheon",sigil:'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 50 50" width="36" height="36"><ellipse cx="25" cy="30" rx="10" ry="12" fill="#4a4a6a" stroke="#c9a84c" stroke-width="1.5"/><ellipse cx="25" cy="22" rx="6" ry="5" fill="#4a4a6a" stroke="#c9a84c" stroke-width="1"/><path d="M19 18 L14 6 M19 18 L12 12 M19 18 L16 8" stroke="#4a4a6a" stroke-width="2.5" stroke-linecap="round" fill="none"/><path d="M31 18 L36 6 M31 18 L38 12 M31 18 L34 8" stroke="#4a4a6a" stroke-width="2.5" stroke-linecap="round" fill="none"/><circle cx="22" cy="21" r="1.5" fill="#1a0a00"/><circle cx="28" cy="21" r="1.5" fill="#1a0a00"/><ellipse cx="19" cy="40" rx="3" ry="5" fill="#4a4a6a" stroke="#c9a84c" stroke-width="1"/><ellipse cx="31" cy="40" rx="3" ry="5" fill="#4a4a6a" stroke="#c9a84c" stroke-width="1"/></svg>',words:'"Ours is the Fury"',region:"The Stormlands",seat:"Storm\'s End",color:"#303050",
    characters:["robert","stannis","renly","gendry"]},
  targaryen:{name:"House Targaryen",sigil:'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 50 50" width="36" height="36"><path d="M25 6 L20 18 L8 18 L18 26 L14 38 L25 30 L36 38 L32 26 L42 18 L30 18 Z" fill="#8b1a1a" stroke="#c9a84c" stroke-width="1.5"/><path d="M25 8 C30 14 38 12 42 18 M25 8 C20 14 12 12 8 18" fill="none" stroke="#c9a84c" stroke-width="1" opacity="0.6"/><circle cx="25" cy="22" r="3" fill="#c9a84c"/><path d="M15 42 C18 36 22 34 25 30 M35 42 C32 36 28 34 25 30" stroke="#8b1a1a" stroke-width="3" fill="none" stroke-linecap="round"/></svg>',words:'"Fire and Blood"',region:"Dragonstone / Essos",seat:"Dragonstone",color:"#602030",
    characters:["daenerys","viserys","rhaegar","aerys"]},
  greyjoy:{name:"House Greyjoy",sigil:'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 50 50" width="36" height="36"><ellipse cx="25" cy="18" rx="10" ry="8" fill="#1a3a5a" stroke="#c9a84c" stroke-width="1.5"/><ellipse cx="25" cy="14" rx="5" ry="3" fill="#2a4a6a"/><path d="M15 24 L10 44 M18 25 L15 46 M22 26 L20 46 M28 26 L30 46 M32 25 L35 46 M35 24 L40 44" stroke="#1a3a5a" stroke-width="3" stroke-linecap="round" fill="none"/><path d="M15 20 C10 16 8 10 12 8 M35 20 C40 16 42 10 38 8" stroke="#1a3a5a" stroke-width="2" fill="none"/><circle cx="21" cy="16" r="1.5" fill="#c9a84c"/><circle cx="29" cy="16" r="1.5" fill="#c9a84c"/></svg>',words:'"We Do Not Sow"',region:"The Iron Islands",seat:"Pyke",color:"#1a2a3a",
    characters:["balon","theon","yara","euron"]},
  tully:{name:"House Tully",sigil:'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 50 50" width="36" height="36"><path d="M8 25 C8 25 20 10 35 20 L44 25 L35 30 C20 40 8 25 8 25Z" fill="#1a4a6a" stroke="#c9a84c" stroke-width="1.5"/><path d="M35 20 L44 15 L42 25 L44 35 L35 30" fill="#1a4a6a" stroke="#c9a84c" stroke-width="1"/><circle cx="16" cy="24" r="2" fill="#c9a84c"/><path d="M20 18 Q25 15 30 18 M20 25 Q25 25 30 25 M20 32 Q25 35 30 32" stroke="#2a6a8a" stroke-width="1" fill="none" opacity="0.7"/></svg>',words:'"Family, Duty, Honour"',region:"The Riverlands",seat:"Riverrun",color:"#1a3a4a",
    characters:["hoster","edmure","catelyn","brynden"]},
  arryn:{name:"House Arryn",sigil:'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 50 50" width="36" height="36"><path d="M25 6 L28 20 L44 16 L32 26 L44 34 L28 30 L25 44 L22 30 L6 34 L18 26 L6 16 L22 20 Z" fill="#2a4a7a" stroke="#c9a84c" stroke-width="1.5"/><path d="M25 12 L27 20 L25 18 L23 20 Z" fill="#c9a84c"/><path d="M14 26 C10 22 8 18 12 16 C14 20 16 22 18 24" fill="#2a4a7a" stroke="#c9a84c" stroke-width="1"/><path d="M36 26 C40 22 42 18 38 16 C36 20 34 22 32 24" fill="#2a4a7a" stroke="#c9a84c" stroke-width="1"/><ellipse cx="25" cy="26" rx="4" ry="4" fill="#1a3a5a" stroke="#c9a84c" stroke-width="1"/><circle cx="25" cy="26" r="1.5" fill="#c9a84c"/></svg>',words:'"As High as Honour"',region:"The Vale",seat:"The Eyrie",color:"#1a3a5a",
    characters:["jon_arryn","lysa","robin"]},
  tyrell:{name:"House Tyrell",sigil:'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 50 50" width="36" height="36"><line x1="25" y1="44" x2="25" y2="20" stroke="#2a6a2a" stroke-width="2.5"/><path d="M25 36 C18 34 14 28 16 22 C20 26 22 30 25 36Z" fill="#2a6a2a"/><path d="M25 36 C32 34 36 28 34 22 C30 26 28 30 25 36Z" fill="#2a6a2a"/><circle cx="25" cy="16" r="8" fill="#8b1a1a" stroke="#c9a84c" stroke-width="1.5"/><path d="M20 16 Q25 10 30 16 Q25 22 20 16Z" fill="#a02020"/><path d="M17 13 Q25 8 33 13" fill="none" stroke="#c9a84c" stroke-width="1" opacity="0.7"/><circle cx="25" cy="16" r="2" fill="#c9a84c"/></svg>',words:'"Growing Strong"',region:"The Reach",seat:"Highgarden",color:"#1a3a1a",
    characters:["mace","olenna","margaery","loras"]},
  martell:{name:"House Martell",sigil:'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 50 50" width="36" height="36"><circle cx="25" cy="25" r="9" fill="#c9a84c" stroke="#8a4a10" stroke-width="1.5"/><line x1="25" y1="4" x2="25" y2="12" stroke="#c9a84c" stroke-width="2.5" stroke-linecap="round"/><line x1="25" y1="38" x2="25" y2="46" stroke="#c9a84c" stroke-width="2.5" stroke-linecap="round"/><line x1="4" y1="25" x2="12" y2="25" stroke="#c9a84c" stroke-width="2.5" stroke-linecap="round"/><line x1="38" y1="25" x2="46" y2="25" stroke="#c9a84c" stroke-width="2.5" stroke-linecap="round"/><line x1="9" y1="9" x2="15" y2="15" stroke="#c9a84c" stroke-width="2" stroke-linecap="round"/><line x1="35" y1="35" x2="41" y2="41" stroke="#c9a84c" stroke-width="2" stroke-linecap="round"/><line x1="41" y1="9" x2="35" y2="15" stroke="#c9a84c" stroke-width="2" stroke-linecap="round"/><line x1="15" y1="35" x2="9" y2="41" stroke="#c9a84c" stroke-width="2" stroke-linecap="round"/><circle cx="25" cy="25" r="4" fill="#8a4a10"/></svg>',words:'"Unbowed, Unbent, Unbroken"',region:"Dorne",seat:"Sunspear",color:"#4a2a10",
    characters:["doran","oberyn","elia","arianne"]}
};

const CHARACTERS = {
  eddard:{name:"Eddard Stark",title:"Lord of Winterfell, Hand of the King",house:"stark",portrait:"🧔",
    bio:"Eddard 'Ned' Stark was Lord of Winterfell and Warden of the North, renowned for his unshakeable honour. Raised alongside Robert Baratheon in the Vale, he fought in Robert's Rebellion. A man carved from grey granite, ill-suited for the vipers' nest of King's Landing.",
    battles:["Siege of Storm's End","Sack of King's Landing","Greyjoy's Rebellion"],
    moments:"His refusal to compromise his honour before the Great Sept of Baelor defined his character until his final breath.",
    lineage_detail:"Father of Robb, Sansa, Arya, Bran, and Rickon. Putative father of Jon Snow.",
    status:"dead",status_text:"Executed at the Sept of Baelor"},
  robb:{name:"Robb Stark",title:"King in the North",house:"stark",portrait:"👦",
    bio:"Undefeated in open battle, the Young Wolf was a commander of rare talent who never lost on the field, yet fell to treachery at the hands of Roose Bolton and Walder Frey at the Red Wedding.",
    battles:["Battle of the Whispering Wood","Battle of the Camps","Battle of Oxcross","The Red Wedding"],
    moments:"His breaking of his betrothal oath to a Frey daughter was the seed of his destruction. His direwolf Grey Wind fell with him at the Twins.",
    lineage_detail:"Son of Eddard and Catelyn Stark.",status:"dead",status_text:"Slain at the Red Wedding"},
  sansa:{name:"Sansa Stark",title:"Lady of Winterfell",house:"stark",portrait:"👸",
    bio:"Raised on songs of knights and fair ladies, Sansa's romantic vision shattered in King's Landing. Hostage to the Lannisters, she endured years of humiliation, learning politics from Cersei and Littlefinger alike.",
    battles:["Battle of the Blackwater (civilian)","Battle of the Bastards"],
    moments:"Her transformation from pawn to player — from King's Landing to the Vale to Winterfell — is one of the great arcs of the age.",
    lineage_detail:"Daughter of Eddard and Catelyn Stark.",status:"alive",status_text:"Queen in the North"},
  arya:{name:"Arya Stark",title:"No One / Arya of House Stark",house:"stark",portrait:"👧",
    bio:"Never content with the life of a lady, Arya trained under Syrio Forel, survived the roads of Westeros in disguise, and crossed the Narrow Sea to study with the Faceless Men in Braavos.",
    battles:["Harrenhal","Various skirmishes across the Riverlands"],
    moments:"Her list became her prayer. Each name crossed off was a debt repaid in the old language of steel.",
    lineage_detail:"Daughter of Eddard and Catelyn Stark.",status:"alive",status_text:"Sailing west of Westeros"},
  bran:{name:"Brandon Stark",title:"The Three-Eyed Raven",house:"stark",portrait:"🧒",
    bio:"Pushed from a tower window by Jaime Lannister, Bran lost his legs but gained greensight. His visions led him beyond the Wall, where he underwent a transformation that left him barely human.",
    battles:["Fall of Winterfell"],
    moments:"Holding the door with Hodor — living the moment twice — is among the most devastating events in the chronicles of ice and fire.",
    lineage_detail:"Son of Eddard and Catelyn Stark.",status:"alive",status_text:"King of the Six Kingdoms"},
  catelyn:{name:"Catelyn Tully",title:"Lady of Winterfell",house:"stark",portrait:"👩",
    bio:"A devoted mother and shrewd noblewoman, Catelyn acted always from love for her children, even when those actions had catastrophic consequences for the realm.",
    battles:["The Red Wedding"],
    moments:"She saw each of her children taken by war or treachery. At the Red Wedding she watched her eldest son slain before her eyes.",
    lineage_detail:"Daughter of Hoster Tully. Mother of Robb, Sansa, Arya, Bran, and Rickon.",
    status:"dead",status_text:"Slain at the Red Wedding"},
  tywin:{name:"Tywin Lannister",title:"Lord of Casterly Rock",house:"lannister",portrait:"👴",
    bio:"The most powerful lord in Westeros for a generation. Cold, calculating, and utterly ruthless, he believed the only thing that mattered was legacy — the Lannister name enduring for a thousand years.",
    battles:["Reyne-Tarbeck Rebellion","Robert's Rebellion — Sack of King's Landing","War of the Five Kings"],
    moments:"The Rains of Castamere was composed to mark his annihilation of House Reyne. The song became a warning played at the Red Wedding.",
    lineage_detail:"Father of Cersei, Jaime, and Tyrion.",status:"dead",status_text:"Killed by Tyrion Lannister"},
  cersei:{name:"Cersei Lannister",title:"Queen Regent of the Seven Kingdoms",house:"lannister",portrait:"👱‍♀️",
    bio:"Twin to Jaime, daughter to Tywin. She married Robert Baratheon and spent twenty years manoeuvring in his court. Brilliant and ruthless, she played the game of thrones better than most men.",
    battles:["Battle of the Blackwater"],
    moments:"Her walk of shame through King's Landing was meant to break her. She emerged transformed — shame burned away, leaving only iron and wildfire.",
    lineage_detail:"Daughter of Tywin. Twin of Jaime. Mother of Joffrey, Myrcella, and Tommen.",
    status:"dead",status_text:"Crushed in the Red Keep's collapse"},
  jaime:{name:"Jaime Lannister",title:"Ser, Knight of the Kingsguard",house:"lannister",portrait:"⚔️",
    bio:"Called the Kingslayer for killing the king he was sworn to protect, Jaime carried that shame for decades — unable to reveal he killed Aerys to save half a million lives from wildfire.",
    battles:["Whispering Wood — captured","Raid on Riverrun"],
    moments:"The loss of his sword hand stripped away his identity entirely. His time with Brienne rebuilt him into something closer to the knight he once dreamed of being.",
    lineage_detail:"Son of Tywin. Twin brother of Cersei.",status:"dead",status_text:"Died with Cersei in the Red Keep"},
  tyrion:{name:"Tyrion Lannister",title:"The Imp, Hand of the Queen",house:"lannister",portrait:"🧙",
    bio:"Born a dwarf and blamed by his father for his mother's death, Tyrion compensated with one of the sharpest minds in the Seven Kingdoms, a gift for wine, and a sardonic wit that disarmed enemies and charmed allies alike.",
    battles:["Battle of the Blackwater — commanded the chain and wildfire"],
    moments:"His trial by combat after Joffrey's murder, and his final confrontation with his father, encapsulate his impossible position as a Lannister who despises what the name demands.",
    lineage_detail:"Son of Tywin. Brother of Cersei and Jaime.",status:"alive",status_text:"Hand of the King, last known"},
  robert:{name:"Robert Baratheon",title:"King of the Seven Kingdoms",house:"baratheon",portrait:"👑",
    bio:"Robert won his throne with a warhammer and a cause. The greatest warrior of his age, he was a catastrophic king — bored by governance, excessive in appetite, mourning Lyanna Stark until his dying day.",
    battles:["Battle of Summerhall","Battle of Ashford","Battle of the Bells","Battle of the Trident"],
    moments:"His killing of Rhaegar at the Trident — rubies scattering across the water — was the defining moment of his life. Everything after was anticlimax.",
    lineage_detail:"Son of Steffon Baratheon. Father of Gendry (bastard).",status:"dead",status_text:"Died of a hunting wound"},
  stannis:{name:"Stannis Baratheon",title:"Lord of Dragonstone, King",house:"baratheon",portrait:"⚖️",
    bio:"The most capable military commander of his age and the most joyless man in Westeros. Stannis did not seek the throne from ambition but from duty — he was the rightful heir and that was sufficient.",
    battles:["Siege of Storm's End","Battle of the Blackwater","Battle of Castle Black"],
    moments:"His sacrifice of his daughter Shireen to the fires of Melisandre shattered any remaining sympathy the realm might have afforded him.",
    lineage_detail:"Son of Steffon Baratheon. Father of Shireen.",status:"dead",status_text:"Executed by Brienne of Tarth"},
  renly:{name:"Renly Baratheon",title:"Lord of Storm's End, King",house:"baratheon",portrait:"🌹",
    bio:"The youngest and most charming of the Baratheon brothers. He raised the greatest army in the realm through force of personality alone — a quality neither Robert nor Stannis possessed.",
    battles:["No major battles — died before engagement"],
    moments:"His shadow-murder by Stannis's sorcery left his army leaderless and ended his kingship before it truly began.",
    lineage_detail:"Son of Steffon Baratheon. Husband of Margaery Tyrell.",status:"dead",status_text:"Killed by shadow assassin"},
  gendry:{name:"Gendry",title:"Lord of Storm's End",house:"baratheon",portrait:"🔨",
    bio:"Robert Baratheon's bastard son, raised as a blacksmith's apprentice. He inherited his father's build and stubbornness but none of his title — until Daenerys legitimised him.",
    battles:["Battle of Winterfell — the Long Night"],
    moments:"His forging of dragonglass weapons before the Long Night gave the realm a fighting chance against the dead.",
    lineage_detail:"Bastard son of Robert Baratheon.",status:"alive",status_text:"Lord of Storm's End"},
  daenerys:{name:"Daenerys Targaryen",title:"Khaleesi, Mother of Dragons, Breaker of Chains",house:"targaryen",portrait:"🐉",
    bio:"Born during a storm on Dragonstone the night her family was destroyed, Daenerys grew up in exile. From slave markets in Essos to the ashes of Valyrian ambition, she forged herself into a queen of fire and blood.",
    battles:["Battle of Yunkai","Battle of Meereen","Siege of Winterfell","Battle of King's Landing"],
    moments:"Stepping into Khal Drogo's funeral pyre and emerging unburnt with three newly-hatched dragons was the moment the world changed forever.",
    lineage_detail:"Daughter of Aerys II and Rhaella Targaryen. Sister of Viserys and Rhaegar.",
    status:"dead",status_text:"Killed by Jon Snow in the throne room"},
  viserys:{name:"Viserys Targaryen",title:"The Beggar King",house:"targaryen",portrait:"👤",
    bio:"The elder brother of Daenerys spent his life nursing his obsession with reclaiming the Iron Throne. He called himself the rightful king but behaved like a petulant child who never understood that dragons choose their riders.",
    battles:["No battles — died before his campaign began"],
    moments:"His golden crown — molten gold poured over his head by Khal Drogo — was the end he earned through cruelty and impatience.",
    lineage_detail:"Son of Aerys II. Brother of Daenerys.",status:"dead",status_text:"Killed by Khal Drogo"},
  rhaegar:{name:"Rhaegar Targaryen",title:"Crown Prince of Dragonstone",house:"targaryen",portrait:"🎵",
    bio:"The finest warrior of his generation and a man of deep melancholy intelligence. His harp-playing moved men to tears. His elopement with Lyanna Stark ignited the rebellion that destroyed his house.",
    battles:["Battle of the Trident"],
    moments:"At the Trident, rubies flew from his breastplate as Robert's warhammer broke him. His secret marriage to Lyanna made their son the true heir.",
    lineage_detail:"Son of Aerys II. Father of Jon Snow by Lyanna Stark.",status:"dead",status_text:"Slain by Robert Baratheon at the Trident"},
  aerys:{name:"Aerys II Targaryen",title:"The Mad King",house:"targaryen",portrait:"🔥",
    bio:"The last Targaryen king began his reign with promise and ended it in madness. His obsession with wildfire and descent into paranoia destroyed three centuries of Targaryen rule.",
    battles:["Defiance of Duskendale","Sack of King's Landing — victim"],
    moments:"His final order — 'Burn them all' — was stopped only by the sword of his own Kingsguard. Jaime Lannister killed him to save half a million lives and was never thanked for it.",
    lineage_detail:"Son of Jaehaerys II. Father of Rhaegar, Viserys, and Daenerys.",
    status:"dead",status_text:"Killed by Jaime Lannister"},
  theon:{name:"Theon Greyjoy",title:"Prince of the Iron Islands",house:"greyjoy",portrait:"⚓",
    bio:"Ward of Eddard Stark since childhood, Theon grew up between two worlds. His seizure of Winterfell shattered both identities, leading to years of captivity that unmade him entirely — until one final act of desperate courage.",
    battles:["Seizure of Winterfell","Battle of Winterfell — the Long Night"],
    moments:"Charging the Night King to protect Bran gave him the death he needed and the realm did not expect.",
    lineage_detail:"Son of Balon Greyjoy. Ward of House Stark.",status:"dead",status_text:"Died charging the Night King"},
  balon:{name:"Balon Greyjoy",title:"King of the Iron Islands",house:"greyjoy",portrait:"🦑",
    bio:"Twice a rebel king, Balon led the Iron Islands to war against Robert Baratheon and lost everything including his sons. His bitterness and pride defined the ironborn ethos of his reign.",
    battles:["Greyjoy's Rebellion"],
    moments:"His rejection of Theon upon his return from Winterfell, and his obsession with the old ways, made him enemies within his own house.",
    lineage_detail:"Father of Yara and Theon.",status:"dead",status_text:"Fell from a bridge at Pyke"},
  yara:{name:"Yara Greyjoy",title:"Lady of the Iron Islands",house:"greyjoy",portrait:"🏴",
    bio:"The eldest surviving child of Balon Greyjoy and the ironborn captain her father always wished Theon had been. Yara led longships before she led kingdoms.",
    battles:["Siege of Deepwood Motte","Various naval engagements"],
    moments:"Her daring attempt to rescue Theon from the Dreadfort showed that beneath ironborn pride ran something rarer — loyalty to blood.",
    lineage_detail:"Daughter of Balon Greyjoy. Sister of Theon.",status:"alive",status_text:"Lady of the Iron Islands"},
  euron:{name:"Euron Greyjoy",title:"King of the Iron Islands",house:"greyjoy",portrait:"⚡",
    bio:"The most dangerous and unpredictable of the Greyjoys, Euron had sailed every sea and murdered his brother Balon to seize the Seastone Chair. His ambition stretched to the Iron Throne itself.",
    battles:["Various naval raids","Battle of Dragonstone waters"],
    moments:"His alliance with Cersei and command of the Golden Company was the most audacious play for power after the War of the Five Kings.",
    lineage_detail:"Son of Quellon Greyjoy. Brother of Balon.",status:"dead",status_text:"Killed by Jaime Lannister"},
  hoster:{name:"Hoster Tully",title:"Lord Paramount of the Riverlands",house:"tully",portrait:"⚜️",
    bio:"Patriarch of House Tully, Hoster built alliances through his daughters' marriages — Catelyn to Eddard Stark, Lysa to Jon Arryn. He died before seeing the consequences of those alliances unfold.",
    battles:["Robert's Rebellion"],
    moments:"His forcing of Lysa to abort Littlefinger's child haunted his deathbed. He died with the word 'tansy' on his lips.",
    lineage_detail:"Father of Catelyn, Lysa, and Edmure.",status:"dead",status_text:"Died of illness at Riverrun"},
  edmure:{name:"Edmure Tully",title:"Lord of Riverrun",house:"tully",portrait:"🐟",
    bio:"The son and heir of Hoster Tully, Edmure was a decent man with a good heart who was consistently outmanoeuvred by circumstances and cleverer enemies.",
    battles:["Battle of Stone Mill","Red Wedding — captured"],
    moments:"His impulsive attack at Stone Mill — well-intentioned and strategically disastrous — exemplified his character perfectly.",
    lineage_detail:"Son of Hoster Tully. Brother of Catelyn and Lysa.",status:"alive",status_text:"Lord of Riverrun"},
  catelyn_tully:{name:"Lysa Tully",title:"Lady of the Eyrie",house:"tully",portrait:"😰",
    bio:"Forced to abort her child by Littlefinger and married to Jon Arryn, Lysa's years in the Eyrie bred paranoid obsessive love. She murdered Jon Arryn at Littlefinger's urging — the spark that ignited the entire conflict.",
    battles:["None"],
    moments:"She died at the Moon Door — pushed through it by the very man she had killed for.",
    lineage_detail:"Daughter of Hoster Tully. Wife of Jon Arryn. Mother of Robin Arryn.",
    status:"dead",status_text:"Pushed through the Moon Door by Littlefinger"},
  brynden:{name:"Brynden Tully",title:"The Blackfish",house:"tully",portrait:"🗡️",
    bio:"The Blackfish refused a marriage arranged for him and spent his life earning his own reputation. One of the finest military commanders of his generation, his unbending character endured to the last.",
    battles:["War of the Ninepenny Kings","Robert's Rebellion","Siege of Riverrun"],
    moments:"His escape from the Red Wedding and defiant last stand at Riverrun — refusing to surrender a castle that was his family's seat — are the acts of a man who bowed to no one.",
    lineage_detail:"Brother of Hoster Tully. Uncle of Catelyn, Lysa, and Edmure.",
    status:"dead",status_text:"Killed during retaking of Riverrun"},
  jon_arryn:{name:"Jon Arryn",title:"Hand of the King, Lord of the Eyrie",house:"arryn",portrait:"🦅",
    bio:"Foster father of both Eddard Stark and Robert Baratheon. His quiet investigation into the secret of Joffrey's parentage set the entire saga in motion — and earned him a poisoner's death.",
    battles:["Robert's Rebellion"],
    moments:"His final words were 'The seed is strong.' His murder — the first in a war that claimed hundreds of thousands — went unavenged for years.",
    lineage_detail:"Lord of the Eyrie. Husband of Lysa Tully. Foster father of Eddard Stark and Robert Baratheon.",
    status:"dead",status_text:"Poisoned by his wife Lysa"},
  lysa:{name:"Lysa Tully",title:"Lady of the Eyrie",house:"arryn",portrait:"😰",
    bio:"Forced to abort her child by Littlefinger and married to Jon Arryn, Lysa's years in the Eyrie bred a paranoid, obsessive love — for Littlefinger, for her son Robin, and for safety above all else.",
    battles:["None"],
    moments:"Her murder of Jon Arryn at Littlefinger's urging was the spark that ignited everything. She died at the Moon Door — pushed through it by the man she had killed for.",
    lineage_detail:"Daughter of Hoster Tully. Wife of Jon Arryn. Mother of Robin Arryn.",
    status:"dead",status_text:"Pushed through the Moon Door by Littlefinger"},
  robin:{name:"Robin Arryn",title:"Lord of the Eyrie",house:"arryn",portrait:"👶",
    bio:"The sickly, spoilt son of Jon Arryn and Lysa Tully, Robin was his mother's obsession and her shield from the world. Wholly unfit for the responsibilities his name demanded.",
    battles:["None"],
    moments:"His casual demands that guests be sent 'through the Moon Door' were a reminder of what unchecked lordly power could become.",
    lineage_detail:"Son of Jon Arryn and Lysa Tully.",status:"alive",status_text:"Lord of the Eyrie"},
  mace:{name:"Mace Tyrell",title:"Lord of Highgarden",house:"tyrell",portrait:"🌸",
    bio:"The lord of the most fertile lands in Westeros was, by universal consensus, pompous and not particularly clever. His greatest accomplishments were his mother's strategies and his children's talents.",
    battles:["Siege of Storm's End — sat and waited"],
    moments:"His 'siege' of Storm's End — doing nothing while Davos smuggled onions to the besieged — became a gentle joke that never fully left him.",
    lineage_detail:"Son of Luthor Tyrell. Father of Margaery and Loras.",status:"dead",status_text:"Killed in the Sept of Baelor explosion"},
  olenna:{name:"Olenna Tyrell",title:"Queen of Thorns",house:"tyrell",portrait:"👵",
    bio:"The sharpest tongue in Westeros. Where her son Mace was pompous and ineffectual, Olenna was the real power behind the Tyrell rose — scheming, witty, and utterly unsentimental.",
    battles:["Political warfare in King's Landing"],
    moments:"'Tell Cersei. I want her to know it was me.' — delivered with serene malice after taking the poison Jaime brought her. One of the great exits in the chronicles.",
    lineage_detail:"Born of House Redwyne. Grandmother of Margaery and Loras.",
    status:"dead",status_text:"Poisoned herself rather than be executed"},
  margaery:{name:"Margaery Tyrell",title:"Queen of the Seven Kingdoms",house:"tyrell",portrait:"🌹",
    bio:"Three times a queen. Margaery possessed an almost supernatural gift for winning people's love. Behind her warmth was a precise political intelligence that matched Cersei's own.",
    battles:["Battle of the Blackwater — political support"],
    moments:"Her mastery of public relations — visiting orphanages, distributing bread — gave her a popularity that Cersei could never match and never forgave.",
    lineage_detail:"Daughter of Mace Tyrell. Granddaughter of Olenna. Married Renly, Joffrey, then Tommen.",
    status:"dead",status_text:"Killed in the Sept of Baelor explosion"},
  loras:{name:"Loras Tyrell",title:"Knight of Flowers",house:"tyrell",portrait:"🗡️",
    bio:"The most celebrated tourney knight of his generation. Loras won hearts across Westeros with his skill and beauty. His private grief at Renly Baratheon's death was the one thing he could never speak of openly.",
    battles:["Battle of the Blackwater","Siege of Dragonstone"],
    moments:"His imprisonment and broken confession extracted by months of captivity were a humiliation his family could not prevent.",
    lineage_detail:"Son of Mace Tyrell. Brother of Margaery.",status:"dead",status_text:"Killed in the Sept of Baelor explosion"},
  doran:{name:"Doran Martell",title:"Prince of Dorne",house:"martell",portrait:"☀️",
    bio:"The cautious elder brother of Oberyn ruled Dorne from his wheelchair with all the speed of the tide — inexorably, if slowly. His plans for revenge against the Lannisters spanned decades.",
    battles:["None directly — a patient strategist"],
    moments:"His revelation to Arianne of his long game — Targaryen alliance, patient accumulation of pieces — showed a mind that thought in years when others thought in days.",
    lineage_detail:"Brother of Oberyn and Elia. Father of Arianne and Quentyn.",
    status:"dead",status_text:"Assassinated by the Sand Snakes"},
  oberyn:{name:"Oberyn Martell",title:"The Red Viper of Dorne",house:"martell",portrait:"🐍",
    bio:"The most dangerous man in Dorne — perhaps in all of Westeros. A warrior, scholar, lover, and poisoner who never forgave and never forgot. He came to King's Landing for justice for his sister Elia.",
    battles:["Various battles in Dorne","Trial by Combat vs. Gregor Clegane"],
    moments:"He had the Mountain beaten. He only needed to finish it — but he wanted a confession first. He wanted the name. That want cost him everything.",
    lineage_detail:"Son of Prince Martell. Brother of Doran and Elia. Father of the Sand Snakes.",
    status:"dead",status_text:"Killed by Gregor Clegane during trial by combat"},
  elia:{name:"Elia Martell",title:"Princess of Dorne, Crown Princess",house:"martell",portrait:"🌺",
    bio:"The gentle, cultured wife of Rhaegar Targaryen and mother of his children, Elia was caught in a war she played no part in making. Her murder during the Sack of King's Landing haunted Dorne for a generation.",
    battles:["None — civilian"],
    moments:"Her death and the manner of it became Oberyn's lifelong wound and Dorne's enduring grievance against the Lannisters. She deserved better than history gave her.",
    lineage_detail:"Daughter of Prince Martell. Wife of Rhaegar Targaryen. Mother of Rhaenys and Aegon.",
    status:"dead",status_text:"Murdered during the Sack of King's Landing"},
  arianne:{name:"Arianne Martell",title:"Princess of Dorne",house:"martell",portrait:"🌙",
    bio:"The elder daughter of Doran and his intended heir, Arianne spent years believing her father planned to disinherit her. Her schemes to crown Myrcella queen were her attempt to seize her destiny before it was taken.",
    battles:["Myrcella incident in the Water Gardens"],
    moments:"Her confrontation with her father — and his revelation of the true depth of his plotting — transformed her understanding of patience and power.",
    lineage_detail:"Daughter of Doran Martell.",status:"alive",status_text:"Princess of Dorne, envoy to the Golden Company"}
};

const LOCATIONS = [
  {id:"winterfell",name:"Winterfell",house:"stark",x:19,y:14,desc:"Seat of House Stark, ancient castle of the Kings of Winter, warmed by hot springs beneath its walls."},
  {id:"kingslanding",name:"King's Landing",house:"baratheon",x:26,y:53,desc:"Capital of the Seven Kingdoms, home of the Iron Throne and the Red Keep."},
  {id:"casterly_rock",name:"Casterly Rock",house:"lannister",x:18,y:44,desc:"Seat of House Lannister, built into a great rock above goldmines of legendary wealth."},
  {id:"dragonstone",name:"Dragonstone",house:"targaryen",x:30,y:50,desc:"Island fortress of House Targaryen. Ancient seat of the heir to the Iron Throne. Dragons were born here."},
  {id:"the_eyrie",name:"The Eyrie",house:"arryn",x:27,y:33,desc:"Sky fortress of House Arryn, perched atop the Mountains of the Moon. Impregnable by force."},
  {id:"highgarden",name:"Highgarden",house:"tyrell",x:18,y:62,desc:"Seat of House Tyrell in the heart of the Reach, the most fertile lands of Westeros."},
  {id:"storms_end",name:"Storm's End",house:"baratheon",x:28,y:62,desc:"Mighty castle of House Baratheon on Shipbreaker Bay, built to face endless storms."},
  {id:"riverrun",name:"Riverrun",house:"tully",x:20,y:39,desc:"Island fortress of House Tully at the fork of the Red Fork and the Tumblestone rivers."},
  {id:"pyke",name:"Pyke",house:"greyjoy",x:10,y:34,desc:"Wave-battered seat of House Greyjoy on the Iron Islands, built on sea stacks above a grey sea."},
  {id:"sunspear",name:"Sunspear",house:"martell",x:27,y:76,desc:"Sandstone seat of House Martell in the deserts of Dorne, ancient and unbowed."},
  {id:"pentos",name:"Pentos",house:null,x:48,y:42,desc:"Free city of Essos where Daenerys Targaryen began her journey to reclaim her birthright."},
  {id:"dothraki",name:"Dothraki Sea",house:null,x:68,y:40,desc:"The great grasslands of Essos, home to the horse lords and their vast khalasars."},
  {id:"the_twins",name:"The Twins",house:null,x:21,y:28,desc:"Twin castles of House Frey straddling the Green Fork. Site of the infamous Red Wedding."},
  {id:"harrenhal",name:"Harrenhal",house:null,x:24,y:40,desc:"The largest castle ever built, now a cursed ruin since Aegon's dragons melted its towers."}
];
